### ISSUE TITLE
nosolite shows the contents of the 0 address if the wallet.pkw file cant be loaded (linux)

### ISSUE THREAD

**Issue by leviable** [Noso-Project/NosoLite#1]
nosolite version: v0.1
OS: ubuntu 20.04

Steps to reproduce:

* Create a new folder and cd into it: `mkdir /tmp/nosolite && cd /tmp/nosolite`
* Copy in the nosolite binary: `cp ~/Downloads/nosolite .`
* Create directory for wallet: `mkdir wallet`
* Create symlink from wallet to a path that doesnt exist: `ln -s NOSODATA/doesntexist wallet/wallet.pkw`
* Start nosolite: `./nosolite`

Expected result:
Nosolite starts and displays an error to the user

Actual result:
Nosolite starts like normal, connects to mainnet, and displays the contents of the 0 address. Also note that the `address` field is blank.

In these two screen shots you can see the symlink to a path that doesn't exist, and what nosolite looks like

![image](https://user-images.githubusercontent.com/11619428/147661609-a41dbf60-c0e1-418b-a3a4-587656a2c956.png)

![image](https://user-images.githubusercontent.com/11619428/147661629-f54f4038-0d9c-4fd3-8350-1d00112134a2.png)

**Comment by ghost** [comment]
This issue has been resolved.
